### ISSUE TITLE
Docs for how to make the R things work on Windows:

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/UBC-MDS.github.io-jekyll#67] opened 2020-08-04 15:57 UTC
Thank you for submitting an issue!

Please only submit bug reports or feature suggestions. Please do not submit support requests and general help questions in this forum.

**Comment by joelostblom** [comment] 2020-08-04 16:46
Closing as duplicate of #68

**Closed as completed by joelostblom** 2020-08-04 16:46 UTC
